version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mailserver:
    image: rnwood/smtp4dev:3.1.4
    container_name: mailserver
    ports:
      - '5000:80'
      - '2525:25'
      - '143:143'
    environment:
      - RelayOptions__Login=$MAILSERVER_USER
      - RelayOptions__Password=$MAILSERVER_PASSWORD
  web:
    container_name: web
    depends_on:
      db:
        condition: service_healthy
      mailserver:
        condition: service_started
    image: tomcat:10-jre17
    volumes:
      - ./target/camperoo-backend.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - CATALINA_OPTS
      - PROFILES_ACTIVE
      - DB_URL
      - DB_USER
      - DB_PASSWORD
      - JWT_SECRET
      - GEOAPIFY_API_KEY
      - RECAPTCHA_SITE
      - RECAPTCHA_SECRET
