version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    image: tomcat:9-jre17
    volumes:
      - ./target/camperoo-backend.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - CATALINA_OPTS
      - PROFILES_ACTIVE
      - DB_URL
      - DB_USER
      - DB_PASSWORD
      - RECAPTCHA_SITE
      - RECAPTCHA_SECRET
