app:
  locale:
    default: en
  security:
    jwt:
      secret: ${JWT_SECRET}
      validMinutes: 15
  auth:
    verificationToken:
      validMinutes: 1440

geoapify:
  apiKey: ${GEOAPIFY_API_KEY}

recaptcha:
  site: ${RECAPTCHA_SITE}
  secret: ${RECAPTCHA_SECRET}
