app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      validMinutes: 15
  auth:
    verificationToken:
      validMinutes: 1440

geoapify:
  apiKey: ${GEOAPIFY_API_KEY}

recaptcha:
  secret: ${RECAPTCHA_SECRET}
