app:
  frontendUrl: ${FRONTEND_URL}
  email:
    sender: noreply@camperoo.pl
  security:
    jwt:
      secret: ${JWT_SECRET}
      validMinutes: 15
    passwordRecoveryToken:
      validMinutes: 60
  user:
    accountCreationToken:
      validMinutes: 1440
  delivery:
    acceptedCountryCodes: pl
  order:
    payment:
      deadlineDays: 7
  file:
    thumbnail:
      heightPx: 250
  scheduling:
    expired-payments-cleanup-cron: 0 5 0 * * ?
    unpaid-orders-cleanup-cron: 0 10 0 * * ?

geoapify:
  apiKey: ${GEOAPIFY_API_KEY}

recaptcha:
  secret: ${RECAPTCHA_SECRET}
