app:
  frontendUrl: ${FRONTEND_URL}
  email:
    sender: noreply@camperoo.pl
  security:
    jwt:
      secret: ${JWT_SECRET}
      validMinutes: 15
    passwordRecoveryToken:
      validMinutes: 60
  user:
    accountCreationToken:
      validMinutes: 1440

geoapify:
  apiKey: ${GEOAPIFY_API_KEY}

recaptcha:
  secret: ${RECAPTCHA_SECRET}
