hibernate:
  show_sql: true
  format_sql: true
  dialect: org.hibernate.dialect.PostgreSQLDialect
  physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  auto_quote_keyword: true
  cache:
    use_query_cache: true
    region:
      factory_class: jcache
    javax:
      cache:
        provider: org.ehcache.jsr107.EhcacheCachingProvider
        uri: ehcache.xml
  hbm2ddl:
    auto: validate
